#!/bin/bash
if [ "$HOSTNAME" = azazel ]; then
        cd ~
        git clone https://github.com/weechat/weechat
        cd weechat
        mkdir build
        cd build
        cmake .. -DENABLE_NLS=OFF -DCMAKE_INSTALL_PREFIX=$HOME
        make
        make install
        echo '*/upgrade ~/bin/weechat' > `find ~/.weechat -name "weechat_fifo_*"`
        rm -rf ~/weechat
else
        printf '%s\n' "uh-oh, not on azazel, ssh azazel and try again"
fi
